#!/usr/bin/env python3

################################################################################
#                                                                              #
# Copyright (C) 2024 Brunk (Anas)                                              #
#                                                                              #
# xsserve v1.0.0  -   Simplify XSS exploitation                                #
#                                                                              #
#                                                                              #
# GNU GENERAL PUBLIC LICENSE                                                   #
#                                                                              #
# This program is free software: you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
################################################################################

from modules.logger import info, error 
from modules.ngrok import killer
from termcolor import colored
from modules.xss import XSS
from random import randint

def banner():
    """
    Display the script banner
    """
    print(
        colored(f"""\n __  _____ ___  ___ _ ____   _____ \n""", "yellow", attrs=["bold"]) +
        colored(f""" \\ \\/ / __/ __|/ _ \\ '__\\ \\ / / _ \\\n""", "yellow", attrs=["bold"]) +
        colored(f"""  >  <\\__ \\__ \\  __/ |   \\ V /  __/""", "yellow", attrs=["bold"]) + colored("    Simplify XSS exploitation\n", "white") +
        colored(f""" /_/\\_\\___/___/\\___|_|    \\_/ \\___|""", "yellow", attrs=["bold"]) + colored("    (", "white") + colored("@NullBrunk", "red") + colored(")\n", "white")
    ) 

if __name__ == "__main__":
    banner()
    info("launching XSS.py")
    
    xss = XSS()
    try:
        xss.run(randint(65000, 65500))
    except KeyboardInterrupt:
        print()
        error("user exit")
    killer()
